# Changes here will be overwritten by Copier
_commit: 2bf2d618f4cc1a4264ce63cd4ece529869b6a270
_src_path: /private/var/folders/01/nglx85yd2fj1t15k_711f0q00000gn/T/copier._vcs.clone.yd1w__o5
author_email: gauthamchettiar@gmail.com
author_name: Gautham Chettiar
license: MIT
project_description: A short description of the project.
project_name: test-uv
project_slug: test_uv
min_python_version: '3.13'
year: '2026'
