# Changes here will be overwritten by Copier
_commit: 8089d51b8b623cbbf456dea56af84ebd2fd3d953
_src_path: /private/var/folders/01/nglx85yd2fj1t15k_711f0q00000gn/T/copier._vcs.clone.etvxs7g9
author_email: gauthamchettiar@gmail.com
author_name: Gautham Chettiar
license: MIT
project_description: A short description of the project.
project_name: test-uv
project_slug: test_uv
min_python_version: '3.13'
year: '2026'
