# Changes here will be overwritten by Copier
_commit: 3bd911fc2d2d616ccb608f52004096e80cf44af7
_src_path: /private/var/folders/01/nglx85yd2fj1t15k_711f0q00000gn/T/copier._vcs.clone.dwcq_bs0
author_email: gauthamchettiar@gmail.com
author_name: Gautham Chettiar
license: MIT
project_description: A short description of the project.
project_name: test-copier-uv
project_slug: test_copier_uv
min_python_version: '3.10'
year: '2026'
