# Changes here will be overwritten by Copier
_commit: e872c2460f2103cff8c283d563ca24c3385102cb
_src_path: /private/var/folders/01/nglx85yd2fj1t15k_711f0q00000gn/T/copier._vcs.clone.i75hqdfi
author_email: gauthamchettiar@gmail.com
author_name: Gautham Chettiar
license: MIT
project_description: A short description of the project.
project_name: test-copier-uv
project_slug: test_copier_uv
min_python_version: '3.10'
year: '2026'
