# Changes here will be overwritten by Copier
_commit: e311345816c36508cb7a3ed6b8b1266f4b5777b3
_src_path: /private/var/folders/01/nglx85yd2fj1t15k_711f0q00000gn/T/copier._vcs.clone.009ath6i
author_email: gauthamchettiar@gmail.com
author_name: Gautham Chettiar
license: MIT
project_description: A short description of the project.
project_name: test-copier-uv
project_slug: test_copier_uv
min_python_version: '3.13'
year: '2026'
