repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [pre-commit]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline, --exclude-lines, '^_commit:']
  - repo: local
    hooks:
      - id: lint-fix-diff-only
        types: [python]
        language: system
        name: poe lint-fix (ruff check fix)
        entry: uv run poe lint-fix
        stages: [pre-commit]
      - id: format-diff-only
        language: system
        types: [python]
        name: poe format (ruff format)
        entry: uv run poe format
        stages: [pre-commit]
      - id: type-check-diff-only
        language: system
        types: [python]
        name: poe type-check (pyright)
        entry: uv run poe type-check
        stages: [pre-commit]
      - id: lint-all
        language: system
        name: poe lint (ruff check)
        entry: uv run poe lint
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: format-check-all
        language: system
        name: poe format-check (ruff check --fix=false)
        entry: uv run poe format-check
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: type-check-all
        language: system
        name: poe type-check (pyright)
        entry: uv run poe type-check
        pass_filenames: false
        always_run: true
        stages: [pre-push]
